apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cat-controller
  namespace: cattopia
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cat-controller
    spec:
      serviceAccountName: cat-controller
      containers:
      - name: cat-controller
        image: github.com/bobcatfish/testing-crds/client-go/cmd/factored-controller
        args: [
          "-logtostderr",
          "-stderrthreshold", "INFO",
        ]