apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: feline-controller-admin
subjects:
  - kind: ServiceAccount
    name: feline-controller
    namespace: felinetopia
roleRef:
  kind: ClusterRole
  name: feline-admin
  apiGroup: rbac.authorization.k8s.io
