apiVersion: v1
kind: Service
metadata:
  labels:
    app: feline-controller
  name: feline-controller
  namespace: felinetopia
spec:
  ports:
  - name: endpoint
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: feline-controller
