apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cat-controller-admin
subjects:
  - kind: ServiceAccount
    name: cat-controller
    namespace: cattopia
roleRef:
  kind: ClusterRole
  name: cat-admin
  apiGroup: rbac.authorization.k8s.io
