apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cat-controller
  namespace: cattopia
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cat-controller
    spec:
      serviceAccountName: cat-controller
      containers:
      - name: cat-controller
        image: github.com/knative/build-pipeline/cmd/controller
        args: [
          "-logtostderr",
          "-stderrthreshold", "INFO",
        ]
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging
